<a href="https://colab.research.google.com/github/judgeadamu123-crypto/Judge-Ginasha-/blob/main/WEEK_6_Pandas_for_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# WEEK 6: Pandas for Data Analysis

**Programme:** Data Science  
**Course Title:** Data Visualization and Storytelling (Practical)  
**Week:** 6  
**Contact Hours:** 2 Hours Lecture + 2 Hours Practical  

---

## 🎯 Objective

Learn how to use Pandas for structured data analysis.

Students will:

- Import Pandas
- Create DataFrames
- Read CSV files
- Explore datasets
- Compute statistics
- Filter data
- Perform basic analysis

NAME GINASHA JUDGE ADAMU

DEPARTMENT DATA SCIENCE

COURSE DTS 101

FACAULTY COMPUTING

In [1]:

import pandas as pd


# 📘 ASSIGNMENT (Week 6)

Using Pandas:

1. Create a new CSV file with at least 10 students.
2. Load the CSV using pd.read_csv().
3. Compute:
   - Subject averages
   - Overall student averages
4. Identify:
   - Top performing student
   - Lowest performing student
5. Export the updated dataset to a new CSV file.

Submit your completed notebook (.ipynb).

In [17]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "john", "job", "mark", "peace","randa","David", "Eva"],
    "Math": [65, 56, 89, 48, 63, 94, 80, 45, 90, 75],
    "English": [70, 85, 60, 95, 48, 68, 57, 50, 88, 80],
    "Science": [72, 94, 68,82,49,58, 78, 48, 92, 79]
}

df = pd.DataFrame(data)
df

      Name  Math  English  Science
0    Alice    65       70       72
1      Bob    56       85       94
2  Charlie    89       60       68
3     john    48       95       82
4      job    63       48       49
5     mark    94       68       58
6    peace    80       57       78
7    randa    45       50       48
8    David    90       88       92
9      Eva    75       80       79

In [18]:

df[["Math", "English", "Science"]].mean()

Math       70.5
English    70.1
Science    72.0
dtype: float64

In [20]:
df["Math"].mean()

np.float64(70.5)

In [21]:
df["English"].mean()

np.float64(70.1)

In [22]:
df["Science"].mean()

np.float64(72.0)

In [25]:
df["Average"] = df[["Math", "English", "Science"]].mean(axis=1)
df["Result"] = df["Average"].apply(lambda x: "Pass" if x >= 50 else "Fail")
df

      Name  Math  English  Science    Average Result
0    Alice    65       70       72  69.000000   Pass
1      Bob    56       85       94  78.333333   Pass
2  Charlie    89       60       68  72.333333   Pass
3     john    48       95       82  75.000000   Pass
4      job    63       48       49  53.333333   Pass
5     mark    94       68       58  73.333333   Pass
6    peace    80       57       78  71.666667   Pass
7    randa    45       50       48  47.666667   Fail
8    David    90       88       92  90.000000   Pass
9      Eva    75       80       79  78.000000   Pass